import {
  approvalRequests,
  auditEvents,
  bankAccounts,
  bankTransactions,
  cashForecasts,
  collectionActions,
  communicationMessages,
  communicationThreads,
  companies,
  companyPolicies,
  criticalObligations,
  customerContacts,
  customers,
  forecastScenarios,
  integrationConnections,
  invoiceLineItems,
  invoices,
  memberships,
  messageDrafts,
  outboxEvents,
  payments,
  promiseToPayRecords,
  sourceObjects,
  syncCursors,
  syncJobs,
  users,
} from "../schema/index.js";
import { createDb, createPool } from "../client.js";

const ids = {
  company: "10000000-0000-4000-8000-000000000001",
  owner: "10000000-0000-4000-8000-000000000002",
  membership: "10000000-0000-4000-8000-000000000003",
  policy: "10000000-0000-4000-8000-000000000004",
  xeroConnection: "10000000-0000-4000-8000-000000000005",
  bankConnection: "10000000-0000-4000-8000-000000000006",
  xeroSyncJob: "10000000-0000-4000-8000-000000000007",
  xeroCursor: "10000000-0000-4000-8000-000000000008",
  bankCursor: "10000000-0000-4000-8000-000000000009",
  northstarSource: "20000000-0000-4000-8000-000000000001",
  brightlaneSource: "20000000-0000-4000-8000-000000000002",
  apexSource: "20000000-0000-4000-8000-000000000003",
  northstarInvoiceSource: "20000000-0000-4000-8000-000000000004",
  brightlaneInvoiceSource: "20000000-0000-4000-8000-000000000005",
  apexInvoiceSource: "20000000-0000-4000-8000-000000000006",
  bankTransactionSource: "20000000-0000-4000-8000-000000000007",
  northstar: "30000000-0000-4000-8000-000000000001",
  brightlane: "30000000-0000-4000-8000-000000000002",
  apex: "30000000-0000-4000-8000-000000000003",
  northstarContact: "30000000-0000-4000-8000-000000000004",
  brightlaneContact: "30000000-0000-4000-8000-000000000005",
  apexContact: "30000000-0000-4000-8000-000000000006",
  northstarInvoice: "40000000-0000-4000-8000-000000000001",
  brightlaneInvoice: "40000000-0000-4000-8000-000000000002",
  apexInvoice: "40000000-0000-4000-8000-000000000003",
  northstarLine: "40000000-0000-4000-8000-000000000004",
  brightlaneLine: "40000000-0000-4000-8000-000000000005",
  apexLine: "40000000-0000-4000-8000-000000000006",
  bankAccount: "50000000-0000-4000-8000-000000000001",
  bankTransaction: "50000000-0000-4000-8000-000000000002",
  payment: "50000000-0000-4000-8000-000000000003",
  payroll: "60000000-0000-4000-8000-000000000001",
  vat: "60000000-0000-4000-8000-000000000002",
  rent: "60000000-0000-4000-8000-000000000003",
  thread: "70000000-0000-4000-8000-000000000001",
  inboundMessage: "70000000-0000-4000-8000-000000000002",
  promise: "70000000-0000-4000-8000-000000000003",
  forecast: "80000000-0000-4000-8000-000000000001",
  forecastScenario: "80000000-0000-4000-8000-000000000002",
  action: "90000000-0000-4000-8000-000000000001",
  draft: "90000000-0000-4000-8000-000000000002",
  approval: "90000000-0000-4000-8000-000000000003",
  audit: "a0000000-0000-4000-8000-000000000001",
  outbox: "a0000000-0000-4000-8000-000000000002",
};

const now = new Date("2026-05-04T09:00:00.000Z");

const invoiceEvidence = [
  {
    kind: "invoice" as const,
    id: ids.northstarInvoice,
    summary: "Northstar invoice RO-1001 is overdue and has the largest near-term cash impact.",
    sourceProvider: "xero",
    sourceTimestamp: "2026-05-04T08:30:00.000Z",
  },
];

async function main() {
  const pool = createPool();
  const db = createDb(pool);

  try {
    await db.transaction(async (tx) => {
      await tx.insert(companies).values({
        id: ids.company,
        displayName: "RunwayOps Demo Ltd",
        legalName: "RunwayOps Demo Ltd",
        slug: "runwayops-demo",
        baseCurrency: "GBP",
        countryCode: "GB",
        timezone: "Europe/London",
        status: "active",
        settingsJson: { demo: true, collectionsTimezone: "Europe/London" },
      }).onConflictDoNothing({ target: companies.id });

      await tx.insert(users).values({
        id: ids.owner,
        email: "founder@runwayops-demo.example",
        displayName: "Avery Founder",
        authProvider: "demo",
        authProviderUserId: "demo-founder",
        status: "active",
        lastLoginAt: now,
      }).onConflictDoNothing({ target: users.id });

      await tx.insert(memberships).values({
        id: ids.membership,
        companyId: ids.company,
        userId: ids.owner,
        role: "owner",
        status: "active",
        joinedAt: now,
      }).onConflictDoNothing({ target: memberships.id });

      await tx.insert(companyPolicies).values({
        id: ids.policy,
        companyId: ids.company,
        policyKey: "collections.approval",
        policyJson: {
          founderApprovalThresholdMinor: 2_000_000,
          blockedPhrases: ["legal action", "final warning"],
        },
        status: "active",
        effectiveFrom: now,
        requiresFounderApproval: true,
      }).onConflictDoNothing({ target: companyPolicies.id });

      await tx.insert(integrationConnections).values([
        {
          id: ids.xeroConnection,
          companyId: ids.company,
          provider: "xero",
          status: "connected",
          displayName: "Xero Demo Organisation",
          connectedByUserId: ids.owner,
          grantedScopes: ["accounting.contacts.read", "accounting.transactions.read"],
          lastSuccessfulSyncAt: now,
          reconnectRequired: false,
          metadataJson: { tenantName: "RunwayOps Demo Ltd" },
        },
        {
          id: ids.bankConnection,
          companyId: ids.company,
          provider: "gocardless_bank_data",
          status: "connected",
          displayName: "Sandbox Business Current Account",
          connectedByUserId: ids.owner,
          grantedScopes: ["balances", "transactions"],
          consentExpiresAt: new Date("2026-07-30T00:00:00.000Z"),
          lastSuccessfulSyncAt: now,
          reconnectRequired: false,
          metadataJson: { institution: "Sandbox Bank UK" },
        },
      ]).onConflictDoNothing({ target: integrationConnections.id });

      await tx.insert(syncJobs).values({
        id: ids.xeroSyncJob,
        companyId: ids.company,
        connectionId: ids.xeroConnection,
        provider: "xero",
        syncType: "incremental_accounting_sync",
        status: "completed",
        startedAt: new Date("2026-05-04T08:28:00.000Z"),
        completedAt: new Date("2026-05-04T08:30:00.000Z"),
        cursorBefore: "2026-05-03T08:30:00.000Z",
        cursorAfter: "2026-05-04T08:30:00.000Z",
        recordsProcessed: 12,
      }).onConflictDoNothing({ target: syncJobs.id });

      await tx.insert(syncCursors).values([
        {
          id: ids.xeroCursor,
          companyId: ids.company,
          connectionId: ids.xeroConnection,
          provider: "xero",
          resourceType: "invoices",
          cursorValue: "2026-05-04T08:30:00.000Z",
          cursorVersion: 1,
          lastSuccessfulSyncAt: now,
          lastEventAt: now,
        },
        {
          id: ids.bankCursor,
          companyId: ids.company,
          connectionId: ids.bankConnection,
          provider: "gocardless_bank_data",
          resourceType: "transactions",
          cursorValue: "cursor-demo-bank-2026-05-04",
          cursorVersion: 1,
          lastSuccessfulSyncAt: now,
          lastEventAt: now,
        },
      ]).onConflictDoNothing({ target: syncCursors.id });

      await tx.insert(sourceObjects).values([
        {
          id: ids.northstarSource,
          companyId: ids.company,
          provider: "xero",
          providerObjectType: "contact",
          providerObjectId: "xero-contact-northstar",
          sourceUpdatedAt: now,
          rawPayload: { name: "Northstar Retail Group", accountNumber: "NORTHSTAR" },
          rawPayloadHash: "sha256-demo-northstar-contact",
          importedAt: now,
        },
        {
          id: ids.brightlaneSource,
          companyId: ids.company,
          provider: "xero",
          providerObjectType: "contact",
          providerObjectId: "xero-contact-brightlane",
          sourceUpdatedAt: now,
          rawPayload: { name: "Brightlane Studios", accountNumber: "BRIGHTLANE" },
          rawPayloadHash: "sha256-demo-brightlane-contact",
          importedAt: now,
        },
        {
          id: ids.apexSource,
          companyId: ids.company,
          provider: "xero",
          providerObjectType: "contact",
          providerObjectId: "xero-contact-apex",
          sourceUpdatedAt: now,
          rawPayload: { name: "Apex Fabrication Ltd", accountNumber: "APEX" },
          rawPayloadHash: "sha256-demo-apex-contact",
          importedAt: now,
        },
        {
          id: ids.northstarInvoiceSource,
          companyId: ids.company,
          provider: "xero",
          providerObjectType: "invoice",
          providerObjectId: "xero-invoice-ro-1001",
          sourceUpdatedAt: now,
          rawPayload: { invoiceNumber: "RO-1001", amountDueMinor: 1850000 },
          rawPayloadHash: "sha256-demo-ro-1001",
          importedAt: now,
        },
        {
          id: ids.brightlaneInvoiceSource,
          companyId: ids.company,
          provider: "xero",
          providerObjectType: "invoice",
          providerObjectId: "xero-invoice-ro-1002",
          sourceUpdatedAt: now,
          rawPayload: { invoiceNumber: "RO-1002", amountDueMinor: 740000 },
          rawPayloadHash: "sha256-demo-ro-1002",
          importedAt: now,
        },
        {
          id: ids.apexInvoiceSource,
          companyId: ids.company,
          provider: "xero",
          providerObjectType: "invoice",
          providerObjectId: "xero-invoice-ro-1003",
          sourceUpdatedAt: now,
          rawPayload: { invoiceNumber: "RO-1003", amountDueMinor: 520000 },
          rawPayloadHash: "sha256-demo-ro-1003",
          importedAt: now,
        },
        {
          id: ids.bankTransactionSource,
          companyId: ids.company,
          provider: "gocardless_bank_data",
          providerObjectType: "bank_transaction",
          providerObjectId: "bank-txn-brightlane-20260504",
          sourceUpdatedAt: now,
          rawPayload: { amountMinor: 740000, direction: "credit" },
          rawPayloadHash: "sha256-demo-bank-brightlane",
          importedAt: now,
        },
      ]).onConflictDoNothing({ target: sourceObjects.id });

      await tx.insert(customers).values([
        {
          id: ids.northstar,
          companyId: ids.company,
          sourceObjectId: ids.northstarSource,
          displayName: "Northstar Retail Group",
          legalName: "Northstar Retail Group Ltd",
          externalRefs: { xeroContactId: "xero-contact-northstar" },
          relationshipTier: "strategic",
          defaultContactId: ids.northstarContact,
          status: "active",
          notes: "Large account. PO-dependent promises need explicit confirmation.",
        },
        {
          id: ids.brightlane,
          companyId: ids.company,
          sourceObjectId: ids.brightlaneSource,
          displayName: "Brightlane Studios",
          legalName: "Brightlane Studios Ltd",
          externalRefs: { xeroContactId: "xero-contact-brightlane" },
          relationshipTier: "standard",
          defaultContactId: ids.brightlaneContact,
          status: "active",
        },
        {
          id: ids.apex,
          companyId: ids.company,
          sourceObjectId: ids.apexSource,
          displayName: "Apex Fabrication",
          legalName: "Apex Fabrication Ltd",
          externalRefs: { xeroContactId: "xero-contact-apex" },
          relationshipTier: "standard",
          defaultContactId: ids.apexContact,
          status: "active",
        },
      ]).onConflictDoNothing({ target: customers.id });

      await tx.insert(customerContacts).values([
        {
          id: ids.northstarContact,
          companyId: ids.company,
          customerId: ids.northstar,
          name: "Priya Shah",
          email: "priya.shah@northstar.example",
          roleTitle: "Finance Manager",
          isPrimary: true,
          status: "active",
        },
        {
          id: ids.brightlaneContact,
          companyId: ids.company,
          customerId: ids.brightlane,
          name: "Miles Harper",
          email: "miles@brightlane.example",
          roleTitle: "Studio Director",
          isPrimary: true,
          status: "active",
        },
        {
          id: ids.apexContact,
          companyId: ids.company,
          customerId: ids.apex,
          name: "Nadia Cole",
          email: "accounts@apexfabrication.example",
          roleTitle: "Accounts",
          isPrimary: true,
          status: "active",
        },
      ]).onConflictDoNothing({ target: customerContacts.id });

      await tx.insert(invoices).values([
        {
          id: ids.northstarInvoice,
          companyId: ids.company,
          customerId: ids.northstar,
          sourceObjectId: ids.northstarInvoiceSource,
          invoiceNumber: "RO-1001",
          issueDate: "2026-03-25",
          dueDate: "2026-04-24",
          status: "overdue",
          amountTotalMinor: 1_850_000n,
          amountDueMinor: 1_850_000n,
          amountPaidMinor: 0n,
          currency: "GBP",
          lastSourceUpdatedAt: now,
        },
        {
          id: ids.brightlaneInvoice,
          companyId: ids.company,
          customerId: ids.brightlane,
          sourceObjectId: ids.brightlaneInvoiceSource,
          invoiceNumber: "RO-1002",
          issueDate: "2026-04-02",
          dueDate: "2026-05-02",
          status: "paid",
          amountTotalMinor: 740_000n,
          amountDueMinor: 0n,
          amountPaidMinor: 740_000n,
          currency: "GBP",
          lastSourceUpdatedAt: now,
        },
        {
          id: ids.apexInvoice,
          companyId: ids.company,
          customerId: ids.apex,
          sourceObjectId: ids.apexInvoiceSource,
          invoiceNumber: "RO-1003",
          issueDate: "2026-04-12",
          dueDate: "2026-05-12",
          status: "sent",
          amountTotalMinor: 520_000n,
          amountDueMinor: 520_000n,
          amountPaidMinor: 0n,
          currency: "GBP",
          lastSourceUpdatedAt: now,
        },
      ]).onConflictDoNothing({ target: invoices.id });

      await tx.insert(invoiceLineItems).values([
        {
          id: ids.northstarLine,
          companyId: ids.company,
          invoiceId: ids.northstarInvoice,
          description: "Receivables operations implementation",
          quantity: "1",
          unitAmountMinor: 1_850_000n,
          amountMinor: 1_850_000n,
          currency: "GBP",
          taxRate: "0.2000",
          accountCode: "200",
        },
        {
          id: ids.brightlaneLine,
          companyId: ids.company,
          invoiceId: ids.brightlaneInvoice,
          description: "Monthly operations support",
          quantity: "1",
          unitAmountMinor: 740_000n,
          amountMinor: 740_000n,
          currency: "GBP",
          taxRate: "0.2000",
          accountCode: "200",
        },
        {
          id: ids.apexLine,
          companyId: ids.company,
          invoiceId: ids.apexInvoice,
          description: "Forecasting configuration",
          quantity: "1",
          unitAmountMinor: 520_000n,
          amountMinor: 520_000n,
          currency: "GBP",
          taxRate: "0.2000",
          accountCode: "200",
        },
      ]).onConflictDoNothing({ target: invoiceLineItems.id });

      await tx.insert(bankAccounts).values({
        id: ids.bankAccount,
        companyId: ids.company,
        connectionId: ids.bankConnection,
        provider: "gocardless_bank_data",
        accountName: "Business Current Account",
        institutionName: "Sandbox Bank UK",
        accountType: "business_current",
        currency: "GBP",
        currentBalanceMinor: 1_240_000n,
        availableBalanceMinor: 1_240_000n,
        balanceAsOf: now,
        consentExpiresAt: new Date("2026-07-30T00:00:00.000Z"),
        status: "active",
        externalRefs: { accountId: "sandbox-business-current" },
      }).onConflictDoNothing({ target: bankAccounts.id });

      await tx.insert(bankTransactions).values({
        id: ids.bankTransaction,
        companyId: ids.company,
        bankAccountId: ids.bankAccount,
        sourceObjectId: ids.bankTransactionSource,
        providerTransactionId: "bank-txn-brightlane-20260504",
        postedAt: new Date("2026-05-04T07:42:00.000Z"),
        bookingDate: "2026-05-04",
        valueDate: "2026-05-04",
        direction: "credit",
        amountMinor: 740_000n,
        currency: "GBP",
        description: "BRIGHTLANE STUDIOS RO-1002",
        counterpartyName: "Brightlane Studios Ltd",
        runningBalanceMinor: 1_240_000n,
        status: "posted",
        matchedInvoiceId: ids.brightlaneInvoice,
        matchConfidence: "high",
        rawCategory: "credit_transfer",
      }).onConflictDoNothing({ target: bankTransactions.id });

      await tx.insert(payments).values({
        id: ids.payment,
        companyId: ids.company,
        customerId: ids.brightlane,
        invoiceId: ids.brightlaneInvoice,
        sourceObjectId: ids.bankTransactionSource,
        bankTransactionId: ids.bankTransaction,
        paymentDate: "2026-05-04",
        postedAt: new Date("2026-05-04T07:42:00.000Z"),
        amountMinor: 740_000n,
        currency: "GBP",
        providerStatus: "posted",
        paymentMethod: "bank_transfer",
        reference: "RO-1002",
      }).onConflictDoNothing({ target: payments.id });

      await tx.insert(criticalObligations).values([
        {
          id: ids.payroll,
          companyId: ids.company,
          obligationType: "payroll",
          counterpartyName: "May Payroll",
          dueDate: "2026-05-07",
          amountMinor: 2_400_000n,
          currency: "GBP",
          criticality: "critical",
          recurrenceRule: "FREQ=MONTHLY;BYMONTHDAY=7",
          manualOrSource: "manual",
          status: "open",
          metadataJson: { employees: 18 },
          notes: "Must clear before 17:00 UK time.",
        },
        {
          id: ids.vat,
          companyId: ids.company,
          obligationType: "tax",
          counterpartyName: "HMRC VAT",
          dueDate: "2026-05-10",
          amountMinor: 680_000n,
          currency: "GBP",
          criticality: "high",
          manualOrSource: "manual",
          status: "open",
          metadataJson: { taxPeriod: "2026-Q1" },
        },
        {
          id: ids.rent,
          companyId: ids.company,
          obligationType: "rent",
          counterpartyName: "Canal Works Landlord",
          dueDate: "2026-05-14",
          amountMinor: 360_000n,
          currency: "GBP",
          criticality: "medium",
          recurrenceRule: "FREQ=MONTHLY;BYMONTHDAY=14",
          manualOrSource: "manual",
          status: "open",
          metadataJson: { premises: "Unit 4" },
        },
      ]).onConflictDoNothing({ target: criticalObligations.id });

      await tx.insert(communicationThreads).values({
        id: ids.thread,
        companyId: ids.company,
        customerId: ids.northstar,
        channel: "email",
        subject: "RO-1001 payment timing",
        status: "open",
        externalRefs: { manualUpload: true },
      }).onConflictDoNothing({ target: communicationThreads.id });

      await tx.insert(communicationMessages).values({
        id: ids.inboundMessage,
        companyId: ids.company,
        threadId: ids.thread,
        customerId: ids.northstar,
        direction: "inbound",
        sentAt: new Date("2026-05-03T15:10:00.000Z"),
        fromAddress: "priya.shah@northstar.example",
        toAddresses: ["finance@runwayops-demo.example"],
        subject: "RO-1001 payment timing",
        bodyText: "We should be able to pay once the PO is released, likely by Friday.",
        bodyHash: "sha256-demo-northstar-message",
        metadataJson: { importedBy: "manual" },
      }).onConflictDoNothing({ target: communicationMessages.id });

      await tx.insert(promiseToPayRecords).values({
        id: ids.promise,
        companyId: ids.company,
        customerId: ids.northstar,
        invoiceId: ids.northstarInvoice,
        sourceMessageId: ids.inboundMessage,
        amountPromisedMinor: 1_850_000n,
        currency: "GBP",
        promisedDate: "2026-05-08",
        promiseType: "conditional",
        conditionText: "Payment depends on PO release.",
        extractedText: "We should be able to pay once the PO is released, likely by Friday.",
        confidenceAtCreation: "0.5200",
        evidenceRefs: [
          ...invoiceEvidence,
          {
            kind: "communication_message",
            id: ids.inboundMessage,
            summary: "Customer gave a PO-dependent Friday payment indication.",
            sourceTimestamp: "2026-05-03T15:10:00.000Z",
          },
        ],
        outcome: "pending",
        createdBy: "ai",
        approvedByUserId: ids.owner,
      }).onConflictDoNothing({ target: promiseToPayRecords.id });

      await tx.insert(cashForecasts).values({
        id: ids.forecast,
        companyId: ids.company,
        generatedAt: now,
        asOfDate: "2026-05-04",
        horizonDays: 14,
        triggerEventIds: [ids.payment, ids.promise],
        cashBalanceMinor: 1_240_000n,
        currency: "GBP",
        riskStatus: "watch",
        shortfallAmountMinor: 1_160_000n,
        forecastJson: {
          expectedReceipts: [
            {
              invoiceId: ids.northstarInvoice,
              expectedDate: "2026-05-08",
              amountMinor: 1_850_000,
              confidence: 0.52,
            },
          ],
          obligations: [
            { obligationId: ids.payroll, dueDate: "2026-05-07", amountMinor: 2_400_000 },
          ],
        },
        evidenceRefs: [
          ...invoiceEvidence,
          {
            kind: "obligation",
            id: ids.payroll,
            summary: "Payroll is due before the conditional Northstar promise date.",
          },
        ],
      }).onConflictDoNothing({ target: cashForecasts.id });

      await tx.insert(forecastScenarios).values({
        id: ids.forecastScenario,
        companyId: ids.company,
        forecastId: ids.forecast,
        scenarioName: "Northstar pays Friday",
        riskStatus: "watch",
        shortfallAmountMinor: 0n,
        scenarioJson: {
          assumesPromiseIds: [ids.promise],
          notes: "Payroll becomes coverable if Northstar confirms PO release and pays by Friday.",
        },
        evidenceRefs: invoiceEvidence,
      }).onConflictDoNothing({ target: forecastScenarios.id });

      await tx.insert(collectionActions).values({
        id: ids.action,
        companyId: ids.company,
        customerId: ids.northstar,
        invoiceId: ids.northstarInvoice,
        promiseId: ids.promise,
        actionKind: "confirm_promise",
        channel: "email",
        tone: "firm",
        status: "awaiting_approval",
        priorityScore: "92.5000",
        expectedCashImpactMinor: 1_850_000n,
        currency: "GBP",
        probabilityOfPayment: "0.6400",
        evidenceConfidence: "0.8200",
        relationshipRiskPenalty: "3.0000",
        actionEffortPenalty: "1.0000",
        requiresApproval: true,
        reason:
          "Northstar has the largest overdue invoice and its conditional promise is the key swing factor for payroll cover.",
        evidenceRefs: invoiceEvidence,
        recommendedAt: now,
        dueDate: "2026-05-04",
      }).onConflictDoNothing({ target: collectionActions.id });

      await tx.insert(messageDrafts).values({
        id: ids.draft,
        companyId: ids.company,
        actionId: ids.action,
        threadId: ids.thread,
        createdByUserId: ids.owner,
        status: "draft",
        channel: "email",
        subject: "RO-1001 payment confirmation",
        bodyText:
          "Hi Priya, thanks for the update. Could you confirm whether the PO has now been released and whether RO-1001 can be paid by Friday 8 May?",
        version: 1,
        modelTraceId: "demo-model-trace-001",
        evidenceRefs: invoiceEvidence,
      }).onConflictDoNothing({ target: messageDrafts.id });

      await tx.insert(approvalRequests).values({
        id: ids.approval,
        companyId: ids.company,
        subjectKind: "collection_action",
        subjectId: ids.action,
        actionId: ids.action,
        assignedToUserId: ids.owner,
        status: "pending",
        riskLevel: "medium",
        contentSnapshot: {
          draftId: ids.draft,
          subject: "RO-1001 payment confirmation",
          bodyText:
            "Hi Priya, thanks for the update. Could you confirm whether the PO has now been released and whether RO-1001 can be paid by Friday 8 May?",
        },
        policyChecks: {
          blockedPhrases: "pass",
          founderApprovalRequired: true,
          reason: "Strategic customer and invoice over threshold.",
        },
        evidenceRefs: invoiceEvidence,
        dueAt: new Date("2026-05-04T17:00:00.000Z"),
      }).onConflictDoNothing({ target: approvalRequests.id });

      await tx.insert(auditEvents).values({
        id: ids.audit,
        companyId: ids.company,
        actorType: "system",
        action: "collection_action.recommended",
        targetKind: "collection_action",
        targetId: ids.action,
        occurredAt: now,
        summary: "Recommended Northstar confirmation request for payroll-risk coverage.",
        afterJson: {
          actionId: ids.action,
          approvalRequestId: ids.approval,
          forecastId: ids.forecast,
        },
        evidenceRefs: invoiceEvidence,
      }).onConflictDoNothing({ target: auditEvents.id });

      await tx.insert(outboxEvents).values({
        id: ids.outbox,
        companyId: ids.company,
        eventType: "collection_action.recommended",
        aggregateType: "collection_action",
        aggregateId: ids.action,
        payloadJson: {
          actionId: ids.action,
          customerId: ids.northstar,
          invoiceId: ids.northstarInvoice,
          approvalRequestId: ids.approval,
        },
        headersJson: { source: "demo_seed" },
        idempotencyKey: "demo:collection_action.recommended:northstar",
        status: "pending",
        attempts: 0,
        availableAt: now,
        auditEventId: ids.audit,
      }).onConflictDoNothing({ target: outboxEvents.id });
    });
  } finally {
    await pool.end();
  }
}

await main();
